### PR TITLE
Adds prependTo option

### PR DESCRIPTION
**Pull request by ejntaylor**
- Adds an option to prepend the element to start of the Dom. Just use the setting prependTo (or continue to use appendTo if you prefer). Use one or the other.

### CODE REVIEW

**Review by thomashigginbotham — CHANGES_REQUESTED** [review]
Thanks for the addition, @raisonon. Would you mind converting the indentation to tabs instead of spaces for consistency with the original code?

**Comment by ejntaylor** [comment]
Ah, so sorry but I'm not sure how. I tried to delete the spaces in Sublime Text and then used Tabs, but it seems to have just included spaces anyway...

**Comment by thomashigginbotham** [comment]
In Sublime Text, you can go to **View > Indentation** and convert spaces to tabs. You can also update your user preferences to show white space characters (set `"draw_white_space": "all"`). This will show spaces as dots and tabs as dashes.

**Comment by ejntaylor** [comment]
Hi thomas, thanks for the help and good to know about that ongoing!

I've pushed those requested updates.

**Review by thomashigginbotham — APPROVED** [review]

**Pull request merged**
